import os
from dotenv import load_dotenv

load_dotenv()

DEFAULT_USERNAME = 'default'
USERNAME = os.getenv('USERNAME', DEFAULT_USERNAME)

DEFAULT_MASTER_DATA_API_DIR = 'default'
MASTER_DATA_API_DIR = os.getenv('MASTER_DATA_API_DIR', DEFAULT_MASTER_DATA_API_DIR)

DEFAULT_DEEPL_AUTH_KEY = 'default'
DEEPL_AUTH_KEY = os.getenv('DEEPL_AUTH_KEY', DEFAULT_DEEPL_AUTH_KEY)

DEFAULT_POSTMAN_API_KEY = 'default'
POSTMAN_API_KEY = os.getenv('POSTMAN_API_KEY', DEFAULT_POSTMAN_API_KEY)

DEFAULT_POSTMAN_BPA_COLLECTION_KEY = 'default'
POSTMAN_BPA_COLLECTION_KEY = os.getenv('POSTMAN_BPA_COLLECTION_KEY', DEFAULT_POSTMAN_BPA_COLLECTION_KEY)
